### ISSUE TITLE
Error in $scope.clearCompletedTodos project angular with promise

### ISSUE THREAD

**Issue by Tilican** [rethinkdb/rethinkdb-example-nodejs#20]
Hello,

On your example todo with angular and promise, the clearCompletedTodos have a little mistake !

```js
$scope.clearCompletedTodos = function () {
  $scope.todos = todos.filter(function (val) {
    return !val.completed;
  });
};
```

Angular don't know todos and todos are not delete from DB ...

Have to change this to 
```js
$scope.clearCompletedTodos = function () {
  var todos = $scope.todos.filter(function (val) {
    return val.completed;
  });
  for (var i = 0; i < todos.length; i++){
    $scope.removeTodo(todos[i]);
  }
};
```

Bye and thx for this example :+1:

**Comment by danielmewes** [comment]
Thanks for reporting the issue and for providing a patch.

@deontologician does this look like the right fix?

**Comment by deontologician** [comment]
It looks like this is from the `todo-angular-express` and `todo-angular-express-promise` directories getting out of sync. This issue is found in the promise example, but not in the other one.

In the non-promise version, we have:

```js
$scope.clearCompletedTodos = function () {
  $scope.todos.forEach(function (todo) {
    if(todo.completed) {
      $scope.removeTodo(todo);
    }
  });
};
```

which is a little cleaner I think

**Comment by deontologician** [comment]
I went ahead and made the change in 6600248

**Comment by deontologician** [comment]
Thanks again @Tilican :)
