### ISSUE TITLE
Adding a realtimeness feature

### ISSUE THREAD

**Issue by tenzan** [rethinkdb/rethinkdb-example-nodejs#22]
Hello!

Any plans to add a realtimeness to the app by using RethinkDB's changefeed feature?

Thanks.

**Comment by AtnNn** [comment]
There are other sample nodejs apps using changefeeds, for example:

* https://github.com/rethinkdb/rethinkdb-example-nodejs-chat
* https://rethinkdb.com/blog/cats-of-instagram/
* https://rethinkdb.com/blog/dogescript-tutorial/
* https://rethinkdb.com/blog/deepstream/

**Comment by iamclaytonray** [comment]
Should probably be closed
