### ISSUE TITLE
returnVals -> returnChanges

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb-example-nodejs#3]
Noticed by Nanami Ringo in http://stackoverflow.com/questions/28237225/insert-error-in-rethindb-using-node

The source is still using `returnVals`:
https://github.com/rethinkdb/rethinkdb-example-nodejs/blob/master/todo-angular-express/app.js#L81
https://github.com/rethinkdb/rethinkdb-example-nodejs/blob/master/todo-angular-express/app.js#L101

https://github.com/rethinkdb/rethinkdb-example-nodejs/blob/master/todo-angular-express-promise/app.js#L46
https://github.com/rethinkdb/rethinkdb-example-nodejs/blob/master/todo-angular-express-promise/app.js#L63

https://github.com/rethinkdb/rethinkdb-example-nodejs/blob/master/todo-angular-koa/app.js#L66
https://github.com/rethinkdb/rethinkdb-example-nodejs/blob/master/todo-angular-koa/app.js#L87

The argument is now called `returnChanges`.

(assigning to @deontologician )

**Comment by deontologician** [comment]
This was done for the express / non-promise version by #7. The promise and koa drivers still need to be done

**Comment by danielmewes** [comment]
Was fixed by https://github.com/rethinkdb/rethinkdb-example-nodejs/pull/13
