### ISSUE TITLE
Impossible to connect the database

### ISSUE THREAD

**Issue by ticruz38** [rethinkdb/rethinkdb-example-nodejs#4]
Hi,
I tried to use the example, I cloned the repo and run npm install everything is installed without error but when I start my node server impossible to open a connection with rethinkDb I got these errors:

Could not open a connection to initialize the database
Could not connect to localhost:28015.
connect ECONNREFUSED

what's wrong?
thanks
Thibaut

**Comment by deontologician** [comment]
Which version of rethinkdb are you using, and where is it set up?

**Comment by ticruz38** [comment]
it is 1.16.3 version when I run rethinkdb in a terminal I have that path:
Initializing directory /Users/whoami/rethinkdb_data

**Comment by danielmewes** [comment]
@ticruz38 could you post the full output of `rethinkdb`? It should print some information about which ports it's binding to.
Does connecting to the web console ( http://localhost:8080 ) work?

**Comment by ticruz38** [comment]
yes it works here is the output
Running rethinkdb 1.16.3 (CLANG 4.2 (clang-425.0.28))...
Running on Darwin 14.1.0 x86_64
Loading data from directory /Users/belenduchene/rethinkdb_data
warn: Cache size does not leave much memory for server and query overhead (available memory: 945 MB).
warn: Cache size is very low and may impact performance.
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on addresses: 127.0.0.1, ::1
To fully expose RethinkDB on the network, bind to all addresses by running rethinkdb with the `--bind all` command line option.

**Comment by danielmewes** [comment]
Thanks for the output.
Hmm I assume the node.js server is running on the same server as the database?

Could you also post the output of `ifconfig`? Maybe there is something special about your network configuration.

**Comment by ticruz38** [comment]
my node server is on port 3000.
what do you mean with the ifconfig output?

**Comment by coffeemug** [comment]
Are you accessing RethinkDB through `localhost`? Does `localhost:8080` work
in the browser? Also, could you try starting RethinkDB with `--bind all`?

`ifconfig` is a command you can type in the console -- could you paste its
output?

- Slava

**Comment by ticruz38** [comment]
sorry my bad as a beginner I thought rethinkdb would start with the node driver, I need to start it from the terminal and then run 'node app.js' right?
thank you guys and sorry for my mistake

**Comment by danielmewes** [comment]
>  I need to start it from the terminal and then run 'node app.js' right?

Yes, sorry for the confusion.

**Comment by danielmewes** [comment]
We'll improve the README file to make the required steps clearer.
