### ISSUE TITLE
Rewrite this thing

### ISSUE THREAD

**Issue by Prinzhorn** [rethinkdb/rethinkdb-example-nodejs#6]
Hey, I'm just getting started with RethinkDB but I'm an experienced Express developer. I was reading https://github.com/rethinkdb/rethinkdb-example-nodejs/blob/master/todo-angular-express/app.js to get me started, but it has some major issues like

* open/closing the connection for every single request that comes in. I don't think this is correct and would probably perform horribly under load. Or is this on purpose? Will the driver do funny things with multiple queries using the same connection in parallel?
* the way errors are handled by using `handleError` is not elegant. Also calling `next` after `handleError` already answered the request is just wrong. Express has error-handling middleware.
* I believe `closeConnection` is **never** called, because no route-handler calls `next`. This probably leaks memory and does bad things.
* this waterfall should be removed https://github.com/rethinkdb/rethinkdb-example-nodejs/blob/master/todo-angular-express/app.js#L149 via https://github.com/caolan/async

If nobody is at it already, I'd like to completely rewrite it to give something back.

I want to remove all the front-end and angular stuff and instead create a plain and simple todo-REST API with some example `curl` calls. No need to clutter this repo with any front-end magic.

Thoughts?

**Comment by deontologician** [comment]
Being the de-facto maintainer of this, yeah it's pretty old and could use some work. As of 2.0, you should basically be able to get away with 1 connection per thread (so one connection on Node). I'd be happy to review it if you want to submit a rewrite

**Comment by deontologician** [comment]
In terms of front-end magic though, I think it's still valuable to have an end-to-end example. So the front end doesn't need to be extensive (or even angular), but it would be nice to show it being hooked up to actual front-end elements. We get requests for that all the time and it'd be nice to keep that property of this example.

**Comment by danielmewes** [comment]
Thanks for bringing it up @Prinzhorn. An update to this would be awesome.

I agree with @deontologician that we should keep the front-end elements.

**Comment by Prinzhorn** [comment]
#7
